import Head from "next/head";

/**
 * Page 9offa
 * Une page dynamic contient les info sur la commande
 */
export default function Qoffa() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>9offa</main>
    </>
  );
}
