import Head from "next/head";

/**
 * Page A Propos
 * Une page static contient les infos du platform
 */
export default function APropos() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>A Propos</main>
    </>
  );
}
