import Head from "next/head";
import { useState } from "react";
import Alimentaire from "~/components/bazar/alimentaire";
import ArtSection from "~/components/bazar/art-section";
import Habillment from "~/components/bazar/habillment";
import ProductsSelect from "~/components/bazar/products-select";

/**
 * Page Bazar
 * Une page dynamic contient les produit alimentaire
 */
export default function Bazar() {
  const [selctedProductType, setSelctedProductsType] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>3andekchy ? 3andi ?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-12">
        {/* Art Section */}
        <ArtSection />
        {/* Product Select */}
        <ProductsSelect
          selctedProductType={selctedProductType}
          selectHabillment={() => setSelctedProductsType(false)}
          selectAlimentaire={() => setSelctedProductsType(true)}
        />
        {/* Habillment */}
        {!selctedProductType && <Habillment />}
        {/* Alimentaire */}
        {selctedProductType && <Alimentaire />}
      </main>
    </>
  );
}
