import Head from "next/head";
import ArtSection from "~/components/contact/art-section";
import ContactForm from "~/components/contact/contact-form";
import ContactInfoSection from "~/components/contact/contact-info-section";

/**
 * Page Contact
 * Une page dynamic contient une formulaire du conatacts
 */
export default function Contact() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen pt-12 font-roboto">
        {/* Art Section */}
        <ArtSection />
        {/* Contacts */}
        <ContactInfoSection />
        {/* Contact Form */}
        <ContactForm />
      </main>
    </>
  );
}
