import Head from "next/head";

/**
 * Page Contact
 * Une page dynamic contient une formulaire du conatacts
 */
export default function Contact() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Contact</main>
    </>
  );
}
