import Head from "next/head";
import ArtSection from "~/components/el-9offa/art-section";
import Basket from "~/components/el-9offa/basket";

/**
 * Page 9offa
 * Une page dynamic contient les info sur la commande
 */
export default function Qoffa() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen pt-16">
        {/* Art Section */}
        <ArtSection />
        {/* Chart Section */}
        <Basket />
      </main>
    </>
  );
}
