import Head from "next/head";
import Ahana from "~/components/home/ahana";
import Carousel from "~/components/home/carousel";

/**
 * Home page
 * Une page static contient les infos du platform
 */
export default function Home() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Hero Section carousel */}
        <Carousel />
        {/* AHNA Section */}
        <Ahana />
      </main>
    </>
  );
}
