import Head from "next/head";
import Ahana from "~/components/home/ahana";
import Carousel from "~/components/home/carousel";
import Concept from "~/components/home/concept";
import Features from "~/components/home/features";
import NotreBut from "~/components/home/notre-but";

/**
 * Home page
 * Une page static contient les infos du platform
 */
export default function Home() {
  return (
    <>
      <Head>
        <title>3andekchy ? 3andi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-16">
        {/* Hero Section carousel */}
        <Carousel />
        {/* AHNA Section */}
        <Ahana />
        {/* Note But Section */}
        <NotreBut />
        {/* Features Section */}
        <Features />
        {/* Concept Section */}
        <Concept />
      </main>
    </>
  );
}
