import Head from "next/head";
import ArtSection from "~/components/mes-produit/art-section";
import Dashboard from "~/components/mes-produit/dashboard";
import PageLoader from "~/components/ui/page-loader";
import { api } from "~/utils/api";

/**
 * Page Mes Produits
 * Une page dynamic contient les produit alimentaire
 */
export default function MesProduits() {
  const { data: products, status } = api.product.getProductsByUser.useQuery();

  if (status === "loading") {
    return <PageLoader />;
  }

  if (!products) {
    return null;
  }

  return (
    <>
      <Head>
        <title>3andekchy ? 3andi ?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-16">
        {/* Art Section */}
        <ArtSection />
        {/* Dashboard */}
        <Dashboard products={products} />
      </main>
    </>
  );
}
